---
- name: Check if certificate already exists.
  stat:
    path: /etc/letsencrypt/live/{{ cert_item.domains | first | replace('*.', '') }}/cert.pem
  register: letsencrypt_cert
  become: yes

- name: Retrieve running services.
  service_facts:
  become: yes

- name: Stop services to allow certbot to generate a cert.
  service:
    name: "{{ item }}"
    state: stopped
  when:
    - item in ansible_facts.services
    - not letsencrypt_cert.stat.exists
  with_items: "{{ certbot_create_standalone_stop_services }}"
  become: yes

- name: Generate new certificate if one doesn't exist.
  command: "{{ certbot_create_command }}"
  when: not letsencrypt_cert.stat.exists
  become: yes

- name: Start services after cert has been generated.
  service:
    name: "{{ item }}"
    state: started
  when:
    - item in ansible_facts.services
    - not letsencrypt_cert.stat.exists
  with_items: "{{ certbot_create_standalone_stop_services }}"
  become: yes
